"""empty message

Revision ID: 5024cf9fea5b
Revises: b1d442c8d788
Create Date: 2022-02-10 15:48:54.197233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5024cf9fea5b'
down_revision = 'b1d442c8d788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('products', 'imageUrl',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'imageUrl',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
